### ISSUE TITLE
In interactive clush, "=" does not work (1.7.3 via EPEL6)

### ISSUE THREAD

**Issue by kent-engstrom** [cea-hpc/clustershell#344] opened 2017-07-12 15:28 UTC
With clustershell-1.7.3-1.el6.noarch from EPEL6, the man page for clush suggests that you can use "=nodeset" to set the nodeset (as well as using "+" and "-" to add and subtract). When trying that:

```
# clush -w n500
Enter 'quit' to leave this interactive mode
Working with nodes: n500
clush> +n501
Working with nodes: n[500-501]
clush> -n500
Working with nodes: n501
clush> =n502
n501: bash: =n502: command not found
clush: n501: exited with exit code 127
clush> 
```

**Comment by degremont** [comment] 2017-07-18 08:47
Thanks for reporting. Actually documentation is partially wrong. ``=`` is used for switching output type. 
You can achieve the intended behaviour using ``@``:

```
[root@nova1 ~] # clush -w nova[1234,2345]
Enter 'quit' to leave this interactive mode
Working with nodes: nova[1234,2345]
clush> @nova1235
Working with nodes: nova1235
clush> =
Switching to gathered output format
clush> =
Switching to standard output format
clush> 
```

man page should be fixed. [Online documentation](http://clustershell.readthedocs.io/en/latest/) should be completed

**Closed** 2017-07-27 19:33 UTC
Labels: bug, Doc
