### ISSUE TITLE
Factorization errors with nodes list (clush is eating my '0')

### ISSUE THREAD

**Issue by nicolasdeferrieres** [cea-hpc/clustershell#288] opened 2016-02-22 12:43 UTC
Hi,

Like a lot a people, I'm using clush to execute commands on several servers (~6000).

I issued a strange behaviour:
Context: 
$ clush --version
clush 1.7
$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.7 (Santiago)

When I put more than 39 servers, there is a strange behaviour (related to the server's name (ending by three digits)), My list:
```
$ cat filelist
ab12-001
ab12-002
ab12-003
ab12-004
ab12-005
ab12-006
ab12-007
ab12-008
ab12-009
ab12-010
ab12-011
ab12-012
ab123-001
ab123-002
ab123-003
ab123-004
ab123-005
ab123-006
ab123-007
ab123-008
ab123-009
ab123-010
ab123-011
ab123-012
ab123-013
ab123-014
ab123-015
ab123-016
ab123-017
ab123-018
ab123-019
ab123-020
ab123-021
ab123-022
ab123-023
ab123-024
ab123-025
ab123-026
ab123-027
ab123-028
```

But when I launch clush with that list (I tried to put the server's list without the paste command (server1,server2...) or using a file (groups.conf or hostfile), it is the same):
```
$ sudo clush -bw $(head -40 filelist | paste -sd,) "uname"
ab123-1: ssh: Could not resolve hostname ab123-1: Name or service not known
ab123-2: ssh: Could not resolve hostname ab123-2: Name or service not known
ab123-3: ssh: Could not resolve hostname ab123-3: Name or service not known
ab123-4: ssh: Could not resolve hostname ab123-4: Name or service not known
ab123-5: ssh: Could not resolve hostname ab123-5: Name or service not known
ab123-6: ssh: Could not resolve hostname ab123-6: Name or service not known
ab123-7: ssh: Could not resolve hostname ab123-7: Name or service not known
ab123-8: ssh: Could not resolve hostname ab123-8: Name or service not known
ab123-9: ssh: Could not resolve hostname ab123-9: Name or service not known
ab123-10: ssh: Could not resolve hostname ab123-10: Name or service not known
ab123-11: ssh: Could not resolve hostname ab123-11: Name or service not known
ab123-12: ssh: Could not resolve hostname ab123-12: Name or service not known
ab123-13: ssh: Could not resolve hostname ab123-13: Name or service not known
ab123-14: ssh: Could not resolve hostname ab123-14: Name or service not known
ab123-15: ssh: Could not resolve hostname ab123-15: Name or service not known
ab123-16: ssh: Could not resolve hostname ab123-16: Name or service not known
ab123-17: ssh: Could not resolve hostname ab123-17: Name or service not known
ab123-18: ssh: Could not resolve hostname ab123-18: Name or service not known
ab123-19: ssh: Could not resolve hostname ab123-19: Name or service not known
ab123-20: ssh: Could not resolve hostname ab123-20: Name or service not known
ab123-21: ssh: Could not resolve hostname ab123-21: Name or service not known
ab123-22: ssh: Could not resolve hostname ab123-22: Name or service not known
ab123-23: ssh: Could not resolve hostname ab123-23: Name or service not known
ab123-24: ssh: Could not resolve hostname ab123-24: Name or service not known
ab123-25: ssh: Could not resolve hostname ab123-25: Name or service not known
ab123-26: ssh: Could not resolve hostname ab123-26: Name or service not known
ab123-27: ssh: Could not resolve hostname ab123-27: Name or service not known
ab123-28: ssh: Could not resolve hostname ab123-28: Name or service not known
ab12-1: ssh: Could not resolve hostname ab12-1: Name or service not known
ab12-2: ssh: Could not resolve hostname ab12-2: Name or service not known
ab12-3: ssh: Could not resolve hostname ab12-3: Name or service not known
ab12-4: ssh: Could not resolve hostname ab12-4: Name or service not known
ab12-5: ssh: Could not resolve hostname ab12-5: Name or service not known
ab12-6: ssh: Could not resolve hostname ab12-6: Name or service not known
ab12-7: ssh: Could not resolve hostname ab12-7: Name or service not known
ab12-8: ssh: Could not resolve hostname ab12-8: Name or service not known
ab12-9: ssh: Could not resolve hostname ab12-9: Name or service not known
ab12-10: ssh: Could not resolve hostname ab12-10: Name or service not known
ab12-11: ssh: Could not resolve hostname ab12-11: Name or service not known
ab12-12: ssh: Could not resolve hostname ab12-12: Name or service not known
clush: ab123-[1-28],ab12-[1-12] (40): exited with exit code 255
```

So, my server's name are modified from ab123-001 to ab123-1, and obvously, it is not the name of the server! And I tried with FQDN, and the behaviuour didn't change.

When I use less than  40 servers, the behaviour is not the same:
```
$ sudo clush -bw $(head -39 filelist | paste -sd,) "uname"
---------------
ab123-[1-27],ab12-[1-12] (39)
---------------
Linux
$
```
It executes correctly the command, and uses the correct names (with three digits after the hyphen), but in the output, we can see that the factorization problem is also here (only in result output).

At the begining, I executed clush with 2200 servers, and by testing with less servers I found that the behaviour change at 40 servers!

I changed the list, I checked that there were no invisible characters (control characters, space...), so I'm pretty sure that the issue is coming from the factorization in clush!

Did someone encounter the same issue/bug?

Thanks.

**Comment by degremont** [comment] 2016-02-22 13:47
You problem could be summarized to:

```
$ head -40 filelist | nodeset -f
ab123-[1-28],ab12-[1-12]

$ head -39 filelist | nodeset -f
ab123-[001-027],ab12-[001-012]
```

But, actually this is a duplicate of #286 

Could you confirm this?

**Comment by nicolasdeferrieres** [comment] 2016-02-22 14:34
Hi,

Thanks, Indeed, it really seems to be a duplicate.

I downloaded, installed the 1.7.1 version on a test server, and it resolved my issue.

**Comment by degremont** [comment] 2016-02-22 14:36
> I downloaded, installed the 1.7.1 version on a test server, and it resolved my issue.
As 1.7.1 is not yet released yet, i assume you install the master branch.

Cool to see this fixed your issue.

**Closed** 2016-02-22 14:37 UTC
Labels: bug, duplicate
