### ISSUE TITLE
clush crashes when the output is a newline

### ISSUE THREAD

**Issue by AdrienDebrie** [cea-hpc/clustershell#249] opened 2015-05-21 07:35 UTC
Hello,
When running a command that only produces a newline:

```
$ clush -w mexico3 "echo"
Exception in thread Task-2:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/ClusterShell/Task.py", line 406, in _thread_start
    self.excepthook(*sys.exc_info())
  File "/usr/lib/python2.7/site-packages/ClusterShell/CLI/Clush.py", line 707, in clush_excepthook
    raise exp
MessageProcessingError: Message OUT has an invalid payload

^CKeyboard interrupt.
rc=130
$
```

Thank you.

**Comment by degremont** [comment] 2015-05-21 07:53
I assume you are gateway as I cannot reproduce this bug in standard mode?

**Comment by AdrienDebrie** [comment] 2015-05-21 07:59
Yes, sorry!

$ cat /etc/clustershell/topology.conf
[Main]
root : gidc0
gidc0 : mexico[0-4,21]

**Comment by degremont** [comment] 2015-05-21 09:15
It seems the bug is in lib/ClusterShell/Communication.py, in StdOutMessage class. Either this should be fixed in base64 decoding (supporting empty output) or when decoding:
~~~
         self.data = None
-        if output:
+        if output is not None:
            self.data_encode(output)
~~~

To be confirmed...

**Comment by thiell** [comment] 2015-07-09 07:05
https://review.gerrithub.io/239301

When testing this patch, I detected a race when sometimes an exception from the Gateway is silently caught... Another patch is coming for that to improve debugging.

**Closed** 2015-07-20 14:11 UTC
Labels: bug, Lib, WIP
