### ISSUE TITLE
sudo permission require password

### ISSUE THREAD

**Issue by kanagasabapathi** [cea-hpc/clustershell#313] opened 2016-06-13 08:35 UTC
When I executing a command clush -w  root@10.10.10.10 -N sudo  jps
if show the error like below

> sudo: no tty present and no ask pass program specified

Any possible to asking the password when executing the command 

In general ssh also show error when type without "-t". It ask the password 

ssh -t root@10.10.10.10 sudo jps

**Comment by degremont** [comment] 2016-06-13 08:39
You can use ``-t`` option also with clush like: ``clush -o-t -l root -w 10.10.10.10 -N sudo jps``
However, the problem is different when you are reaching several nodes, like:

``
clush -o-t -l root -w 10.10.10.[10-20] -N sudo jps
``

This mean you will have 10 sudo asking for a password.

**Comment by kanagasabapathi** [comment] 2016-06-13 08:55
Still It returns error like below

`clush -o-t -l root -w  10.10.10.10 -N sudo  jps`

Pseudo-terminal will not be allocated because stdin is not a terminal.
sudo: no tty present and no askpass program specified
clush: 10.10.10.10: exited with exit code 1

**Comment by thiell** [comment] 2016-06-13 15:20
@kanagasabapathi this is a duplicate of #234 (sudo with password and requiretty). There is a workaround to send password through stdin that seemed to work, but your ticket reminds me that we should work on sudo support :)

Note that you should use `-o-tt` (or `-o'-t -t'`) to force tty allocation (see man ssh).

Please follow up in #234.

**Closed by thiell** 2016-06-13 15:20 UTC
