### ISSUE TITLE
NodeSet adds leading zeros to node names

### ISSUE THREAD

**Issue by volans-** [cea-hpc/clustershell#404] opened 2019-05-03 23:20 UTC
It seems that NodeSet has a bug while grouping elements if some of them have leading zeros and some not, that causes the leading zeros to be added to the other elements too, causing the alteration of the elements in the NodeSet.

Example code:
```python
>>> from ClusterShell import __version__
>>> __version__
'1.8.1'
>>> from ClusterShell.NodeSet import NodeSet
>>> str(NodeSet('a1.example.com,a01.example.com'))
'a01.example.com'
>>> str(NodeSet('a1.example.com,a02.example.com'))
'a[01-02].example.com'
>>> str(NodeSet('a1.example.com,a002.example.com'))
'a[001-002].example.com'
```

**Comment by degremont** [comment] 2019-05-04 10:32
Duplicate of #293

**Closed by degremont** 2019-05-04 10:32 UTC
Labels: duplicate
