### ISSUE TITLE
Performance Issue with Node Aggregation: `treemode` Command Execution Time for `whoami`

### ISSUE THREAD

**Issue by luxiaoyong** [cea-hpc/clustershell#565] opened 2024-08-31 03:08 UTC
### Issue Description

I am using `treemode` to execute the command `whoami` in an environment with over 1000 nodes. The execution took 17 minutes for this simple command, and for more complex commands, the process almost gets stuck.

#### Example Nodes

Here are a few example nodes in our environment:

- `aa-bb-YYYYYY-ddddd-X01Y07Z15-555-666-0804-eeeeeeee`
- `aa-bb-YYYYYY-ddddd-X01Y07Z18-555-666-0805-eeeeeeee`
- `aa-bb-YYYYYY-ddddd-X01Y07Z21-555-666-0806-eeeeeeee`
- `aa-bb-YYYYYY-ddddd-X01Y07Z24-555-666-0807-eeeeeeee`
- `aa-bb-YYYYYY-ddddd-X01Y07Z27-555-666-0808-eeeeeeee`
- `aa-bb-YYYYYY-ddddd-X01Y07Z30-555-666-0809-eeeeeeee`

#### Topology Configuration

The `topology.conf` file content is as follows:

```ini
[routes]
manage-vm2:manage-vm3,manage-vm1
manage-vm3:aa-bb-YYYYYY-ddddd-X01Y07Z15-555-666-0804-eeeeeeee,aa-bb-YYYYYY-ddddd-X01Y07Z18-555-666-0805-eeeeeeee,aa-bb-YYYYYY-ddddd-X01Y07Z21-555-666-0806-eeeeeeee,aa-bb-YYYYYY-ddddd-X01Y07Z24-555-666-0807-eeeeeeee,aa-bb-YYYYYY-ddddd-X01Y07Z27-555-666-0808-eeeeeeee
manage-vm1:aa-bb-YYYYYY-ddddd-X01Y07Z30-555-666-0809-eeeeeeee
```

#### Problematic Command

The command causing the issue is:

```bash
clush -o-q -w aa-bb-YYYYYY-ddddd-X01Y07Z15-555-666-0804-eeeeeeee,aa-bb-YYYYYY-ddddd-X01Y07Z18-555-666-0805-eeeeeeee whoami
```

#### Observations

- Aggregation of nodes appears to be problematic. When using nodes that can be aggregated, the execution is very fast.

#### Request
- The 1000 node environment is frequently used and the nodes name can not be aggregated.
Can the algorithm or configuration be optimized to improve performance and handle aggregation more efficiently for the nodes listed in our environment?

---

Feel free to adjust any details as needed!

**Comment by thiell** [comment] 2024-09-03 02:14
Duplicate of #560. Improved on master as much as possible. However, note that clustershell is primarily optimized for node names that can be folded, eg. `node[0001-1000]` (or with multiple dimensions like `rack[00-20]node[00-30]`), commonly used for HPC clusters, not random node names that cannot be merged.

**Closed by thiell** 2024-09-03 02:14 UTC
