### ISSUE TITLE
Incorrect name resolution in clush group

### ISSUE THREAD

**Issue by rvucera** [cea-hpc/clustershell#381] opened 2018-06-07 19:11 UTC
Version
----------

```
[mapr@mapr001 clustershell]$ clush --version
clush 1.8
```

Basic problem
----------

Using clustershell to communicate across our mapr cluster and running into problem where the program seems to be trying to resolve host names that are different from the names explicitly given to the program, eg.

Say I have a group file `/etc/clustershell/groups.d/local.cfg` looking like

```
[root@mapr001 hadoop-2.7.0]# cat /etc/clustershell/groups.d/local.cfg
all: mapr[001-006],mapr07
clients: mapr[07]
```

The results of using these groupings are as follows:

```
[root@mapr001 hadoop-2.7.0]# clush -b -g all date
mapr007: ssh: Could not resolve hostname mapr007: Temporary failure in name resolution
---------------
mapr[001-006] (6)
---------------
Fri May 18 08:45:40 HST 2018
clush: mapr007: exited with exit code 255

[root@mapr001 hadoop-2.7.0]# clush -b -g clients date
---------------
mapr07
---------------
```

As shown, we see that the all group is turning "mapr07" into "mapr007" which is not what was written in the config file (yet still able to correctly contact mapr07 when using a group that contains only that node). (This happens even if separating hostname with space rather then comma). 

More details
----------

Running a simple command with the debugging option, I see:

```
[root@mapr001 groups.d]# ls
cluster.yaml.example  local.cfg  README
[root@mapr001 groups.d]#
[root@mapr001 groups.d]#
[root@mapr001 groups.d]# pwd
/etc/clustershell/groups.d
[root@mapr001 groups.d]#
[root@mapr001 groups.d]#
[root@mapr001 groups.d]# vi local.cfg
[root@mapr001 groups.d]#
[root@mapr001 groups.d]#
[root@mapr001 groups.d]# cat local.cfg
.....
all: mapr[001-006],mapr07
.....
[root@mapr001 groups.d]#
[root@mapr001 groups.d]#
[root@mapr001 groups.d]# clush -d -b -g all date
DEBUG:root:clush: STARTING DEBUG
DEBUG:ClusterShell.NodeUtils:EXEC '[ -f /etc/clustershell/groups ] && f=/etc/clustershell/groups || f=/etc/clustershell/groups.d/local.cfg; sed -n 's/^all:\(.*\)/\1/p' $f'
DEBUG:ClusterShell.NodeUtils:READ 'mapr[001-006],mapr07'
Adding nodes from option -g all: mapr[001-007]
Changing max open files soft limit from 65536 to 8192
User interaction: True
Create STDIN worker: False
clush: nodeset=mapr[001-007] fanout=64 [timeout conn=15.0 cmd=0.0] command="date"
SSHCLIENT: ssh -oForwardAgent=no -oForwardX11=no -oConnectTimeout=15 -oBatchMode=yes mapr001 date
SSHCLIENT: ssh -oForwardAgent=no -oForwardX11=no -oConnectTimeout=15 -oBatchMode=yes mapr002 date
SSHCLIENT: ssh -oForwardAgent=no -oForwardX11=no -oConnectTimeout=15 -oBatchMode=yes mapr003 date
SSHCLIENT: ssh -oForwardAgent=no -oForwardX11=no -oConnectTimeout=15 -oBatchMode=yes mapr004 date
SSHCLIENT: ssh -oForwardAgent=no -oForwardX11=no -oConnectTimeout=15 -oBatchMode=yes mapr005 date
SSHCLIENT: ssh -oForwardAgent=no -oForwardX11=no -oConnectTimeout=15 -oBatchMode=yes mapr006 date
SSHCLIENT: ssh -oForwardAgent=no -oForwardX11=no -oConnectTimeout=15 -oBatchMode=yes mapr007 date
mapr001: Wed Jun  6 10:08:57 HST 2018
mapr006: Wed Jun  6 10:08:57 HST 2018
mapr005: Wed Jun  6 10:08:57 HST 2018
mapr002: Wed Jun  6 10:08:57 HST 2018
mapr004: Wed Jun  6 10:08:57 HST 2018
mapr003: Wed Jun  6 10:08:58 HST 2018
mapr007: ssh: Could not resolve hostname mapr007: Temporary failure in name resolution
mapr007: ssh: Could not resolve hostname mapr007: Temporary failure in name resolution
---------------
mapr[001-002,004-006] (5)
---------------
Wed Jun  6 10:08:57 HST 2018
---------------
mapr003
---------------
Wed Jun  6 10:08:58 HST 2018
clush: mapr007: exited with exit code 255
EnginePort: dropped msg: (<function _abort at 0x13e5b18>, (False,), {})
[root@mapr001 groups.d]#
[root@mapr001 groups.d]#
[root@mapr001 groups.d]# vi local.cfg
[root@mapr001 groups.d]#
[root@mapr001 groups.d]#
[root@mapr001 groups.d]# cat local.cfg
.....
#all: mapr[001-006],mapr07
all: mapr07
.....
[root@mapr001 groups.d]#
[root@mapr001 groups.d]#
[root@mapr001 groups.d]# clush -d -b -g all date
DEBUG:root:clush: STARTING DEBUG
DEBUG:ClusterShell.NodeUtils:EXEC '[ -f /etc/clustershell/groups ] && f=/etc/clustershell/groups || f=/etc/clustershell/groups.d/local.cfg; sed -n 's/^all:\(.*\)/\1/p' $f'
DEBUG:ClusterShell.NodeUtils:READ 'mapr07'
Adding nodes from option -g all: mapr07
Changing max open files soft limit from 65536 to 8192
User interaction: True
Create STDIN worker: False
clush: nodeset=mapr07 fanout=64 [timeout conn=15.0 cmd=0.0] command="date"
SSHCLIENT: ssh -oForwardAgent=no -oForwardX11=no -oConnectTimeout=15 -oBatchMode=yes mapr07 date
mapr07: Wed Jun  6 10:09:48 HST 2018
---------------
mapr07
---------------
Wed Jun  6 10:09:48 HST 2018
```

notice the lines

```
DEBUG:ClusterShell.NodeUtils:READ 'mapr[001-006],mapr07'
Adding nodes from option -g all: mapr[001-007]
```

This seems very weird to me.

**Comment by thiell** [comment] 2018-06-08 15:05
Hey @rvucera! Thanks for your detailed report. This is indeed a known limitation of ClusterShell if you mix similar nodes with different zero-padding, like in your case `map001` (pad=3) and `map07` (pad=2). This is actually a duplicate of #293.

The current limitations are described here:
https://clustershell.readthedocs.io/en/latest/tools/nodeset.html#zero-padding

Originally, we didn't think people would use different zero-padding levels for node names in a cluster, as it might be confusing.

However, I agree it is a defect that should be fixed, and we now received several reports of the problem. The plan is to fix it in version 1.9 (#293 is set as a blocker).

**Comment by thiell** [comment] 2018-06-08 15:07
this issue is a duplicate of #293

**Closed** 2018-06-08 15:08 UTC
Labels: duplicate

**Comment by degremont** [comment] 2018-06-08 17:55
Duplicate of #293
